import {authClient,database} from '@/lib/supabase/server';
import {initialData} from '@/lib/geography';
import {validData} from '@/lib/validate';
export const dynamic='force-dynamic';
function answer(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
async function identity(){const client=await authClient();const {data:{user}}=await client.auth.getUser();return user;}
async function access(id:string,user:string){const db=database();const {data:c,error}=await db.from('campaigns').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!c)return null;if(c.owner===user)return {...c,role:'gm'};const {data:m,error:e}=await db.from('memberships').select('user_id').eq('campaign',id).eq('user_id',user).maybeSingle();if(e)throw e;return m?{...c,role:'player'}:null;}
export async function GET(req:Request){try{const u=await identity();if(!u)return answer({error:'請先登入以載入戰役',signedOut:true},401);const db=database(),id=new URL(req.url).searchParams.get('id');if(!id){const own=await db.from('campaigns').select('id').eq('owner',u.id);const joined=await db.from('memberships').select('campaign').eq('user_id',u.id);if(own.error||joined.error)throw own.error||joined.error;const campaigns=[...own.data.map(c=>({id:c.id,role:'gm'})),...joined.data.filter(m=>!own.data.some(c=>c.id===m.campaign)).map(m=>({id:m.campaign,role:'player'}))];return answer({campaigns});}const c=await access(id,u.id);if(!c)return answer({error:'無權存取此戰役'},403);const d=c.data;if(c.role!=='gm')d.places=d.places.filter((p:any)=>!p.hidden).map(({gmNotes,...p}:any)=>p);const notes=await db.from('notes').select('location,body').eq('campaign',id).eq('user_id',u.id);if(notes.error)throw notes.error;return answer({id,role:c.role,revision:c.revision,data:d,notes:Object.fromEntries(notes.data.map(n=>[n.location,n.body])),...(c.role==='gm'?{invite:c.invite}:{})});}catch(e){console.error('Campaign load failed');return answer({error:'載入失敗，請稍後重試'},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return answer({error:'來源不符'},403);const u=await identity();if(!u)return answer({error:'請先登入'},401);const text=await req.text();if(text.length>1500000)return answer({error:'內容太大'},413);const body=JSON.parse(text),db=database();
 if(body.action==='create'||body.action==='import'){
  let data=initialData;let notes:Record<string,string>={};
  if(body.action==='import'){const b=body.backup;if(b?.format!=='dnd-map-backup'||b.version!==1||!validData(b.data)||!b.notes||typeof b.notes!=='object'||Array.isArray(b.notes)||Object.entries(b.notes).some(([id,value])=>!b.data.places.some((p:any)=>p.id===id)||typeof value!=='string'||value.length>20000))return answer({error:'備份格式不符'},400);data=b.data;notes=b.notes;}
  const {data:c,error}=await db.from('campaigns').insert({owner:u.id,data}).select('id').single();if(error)throw error;
  if(Object.keys(notes).length){const {error:e}=await db.from('notes').insert(Object.entries(notes).map(([location,body])=>({campaign:c.id,user_id:u.id,location,body})));if(e){await db.from('campaigns').delete().eq('id',c.id).eq('owner',u.id);throw e;}}
  return answer({id:c.id});
 }
 if(body.action==='join'){const {data:c,error}=await db.from('campaigns').select('id').eq('invite',String(body.invite||'')).maybeSingle();if(error||!c)return answer({error:'邀請碼無效'},404);const {error:e}=await db.from('memberships').upsert({campaign:c.id,user_id:u.id},{onConflict:'campaign,user_id',ignoreDuplicates:true});if(e)throw e;return answer({id:c.id});}
 if(typeof body.id!=='string')return answer({error:'缺少戰役'},400);const c=await access(body.id,u.id);if(!c)return answer({error:'無權存取此戰役'},403);
 if(body.action==='note'){if(typeof body.body!=='string'||body.body.length>20000||!c.data.places.some((p:any)=>p.id===body.location&&(c.role==='gm'||!p.hidden)))return answer({error:'筆記或地點無效'},400);const {error}=await db.from('notes').upsert({campaign:body.id,user_id:u.id,location:body.location,body:body.body},{onConflict:'campaign,user_id,location'});if(error)throw error;return answer({ok:true});}
 if(c.role!=='gm')return answer({error:'只有 GM 可以編輯戰役資料'},403);
 if(body.action==='save'){if(!validData(body.data)||!Number.isInteger(body.revision))return answer({error:'地圖資料格式不符'},400);const {data:rows,error}=await db.from('campaigns').update({data:body.data,revision:body.revision+1}).eq('id',body.id).eq('owner',u.id).eq('revision',body.revision).select('revision');if(error)throw error;if(!rows.length)return answer({error:'另一個視窗已更新地圖。請先保留你的編輯，再重新載入。'},409);return answer({revision:rows[0].revision});}
 return answer({error:'操作不存在'},400);
 }catch(e){console.error('Campaign mutation failed');return answer({error:'儲存失敗，編輯內容仍保留在畫面上，請重試'},503);}}
