import assert from 'node:assert/strict';
import {GET,POST} from '../app/api/atlas/route';
import {setUser} from './fake-platform';
import {initialData} from '../lib/geography';
import {planRoute} from '../lib/routing';
const get=(id='')=>GET(new Request('https://map.test/api/atlas'+(id?'?id='+id:'')));
const post=(body:any)=>POST(new Request('https://map.test/api/atlas',{method:'POST',headers:{origin:'https://map.test'},body:JSON.stringify(body)}));
setUser(null);assert.equal((await get()).status,401);
setUser('gm');const created=await (await post({action:'create'})).json();const original=await (await get(created.id)).json();const d=structuredClone(original.data);d.places[0].gmNotes='GM-PRIVATE-CANARY';d.places[1].hidden=true;
assert.equal((await post({action:'save',id:created.id,revision:0,data:d})).status,200);
assert.equal((await post({action:'save',id:created.id,revision:0,data:d})).status,409);
setUser('outsider');assert.equal((await get(created.id)).status,403);
setUser('player');assert.equal((await post({action:'join',invite:original.invite})).status,200);const player=await(await get(created.id)).json();assert.equal(player.role,'player');assert.ok(!JSON.stringify(player).includes('GM-PRIVATE-CANARY'));assert.ok(!player.data.places.some((p:any)=>p.id===d.places[1].id));assert.equal(player.invite,undefined);
assert.equal((await post({action:'save',id:created.id,revision:1,data:d})).status,403);
assert.equal((await post({action:'note',id:created.id,location:d.places[1].id,body:'hidden'})).status,400);
assert.equal((await post({action:'note',id:created.id,location:d.places[0].id,body:'PLAYER-PRIVATE-CANARY'})).status,200);
setUser('gm');assert.ok(!JSON.stringify(await(await get(created.id)).json()).includes('PLAYER-PRIVATE-CANARY'));
const backup={format:'dnd-map-backup',version:1,data:d,notes:{[d.places[0].id]:'GM own note'}};
const imported=await(await post({action:'import',backup})).json();assert.notEqual(imported.id,created.id);const restored=await(await get(imported.id)).json();assert.deepEqual(restored.data,d);assert.deepEqual(restored.notes,backup.notes);assert.notEqual(restored.invite,original.invite);
assert.equal((await post({action:'import',backup:{...backup,version:99}})).status,400);
const zh=planRoute(['triboar','yartar'],'road',initialData.places,'zh'),en=planRoute(['triboar','yartar'],'road',initialData.places,'en');assert.deepEqual(zh.points,en.points);assert.equal(zh.miles,en.miles);assert.ok(en.towns.includes('Triboar'));
console.log('PASS: authentication, GM/player isolation, notes privacy, revisions, backup import, bilingual routing. Mock database; live Supabase still requires verification.');
