'use client';
import {useState,useEffect,useRef,useMemo} from 'react';
import {Compass,MapPin,Route,Layers,Shield,Users,Plus,Minus,RotateCcw,Save,Trash2,GripVertical,Eye,EyeOff,Lock,ChevronRight,MousePointer2,Pencil,Check,X,Search,Link as LinkIcon,Mountain,Navigation,Flag,StickyNote,TriangleAlert} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Checkbox} from '@/components/ui/checkbox';
import {Tooltip,TooltipContent,TooltipTrigger,TooltipProvider} from '@/components/ui/tooltip';
import {toast,Toaster} from 'sonner';
import {initialData,roads,MAP_HEIGHT,sourceLinks} from '@/lib/geography';
import {useLocale} from '@/lib/use-locale';
import {planRoute} from '@/lib/routing';
import type {Place,AtlasData,Session,Point,MapObject,MapObjectKind,MapObjectVisibility} from '@/lib/types';
import {MAP_LAYER_ORDER} from '@/lib/map-layers';
const emptyDraft={info:'',gmNotes:'',note:'',faction:'',hidden:false};
function Pick({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{id:string;name:string}[];label:string}){return <Select value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent><SelectItem value="__none">{label}</SelectItem>{items.map(i=><SelectItem key={i.id} value={i.id}>{i.name}</SelectItem>)}</SelectContent></Select>}
export default function Atlas(){
 const {locale,setLocale,tr,name}=useLocale();
 const [data,setData]=useState<AtlasData>(initialData),[session,setSession]=useState<Session|null>(null),[mapObjects,setMapObjects]=useState<MapObject[]>([]),[loading,setLoading]=useState(true),[signedOut,setSignedOut]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const [mode,setMode]=useState('gm'),[tab,setTab]=useState('route'),[search,setSearch]=useState(''),[selected,setSelected]=useState<string|null>(null),[sheet,setSheet]=useState(false),[draft,setDraft]=useState(emptyDraft),[hover,setHover]=useState<{p:Place;x:number;y:number}|null>(null);
 const [stops,setStops]=useState<string[]>(['triboar','yartar']),[travel,setTravel]=useState('road'),[routePick,setRoutePick]=useState(false),[view,setView]=useState({x:340,y:10,w:330,h:280}),[showLabels,setShowLabels]=useState(true),[showRegions,setShowRegions]=useState(true);
 const [draw,setDraw]=useState(false),[polygon,setPolygon]=useState<Point[]>([]),[activeFaction,setActiveFaction]=useState(''),[factionName,setFactionName]=useState(''),[factionColor,setFactionColor]=useState('#bf5d48'),[movePlace,setMovePlace]=useState<string|null>(null),[invite,setInvite]=useState(''),[inviteShown,setInviteShown]=useState(false);
 const [objectPlacement,setObjectPlacement]=useState<MapObjectKind|null>(null),[objectSheet,setObjectSheet]=useState(false),[editingObject,setEditingObject]=useState<MapObject|null>(null),[objectDraft,setObjectDraft]=useState({kind:'note' as MapObjectKind,x:0,y:0,radius:null as number|null,label:'',content:'',visibility:'gm_private' as MapObjectVisibility});
 const svg=useRef<SVGSVGElement>(null),[campaigns,setCampaigns]=useState<{id:string;role:string}[]>([]),drag=useRef<any>(null),skipClick=useRef(false),dragMarker=useRef<string|null>(null),markerStart=useRef<Point>([0,0]),dragObject=useRef<any>(null);
 const isGM=session?.role==='gm',canEdit=isGM&&mode==='gm',displayPlaces=useMemo(()=>data.places.filter(p=>mode==='gm'&&isGM||!p.hidden),[data,isGM,mode]);
 const displayMapObjects=useMemo(()=>isGM&&mode==='player'?mapObjects.filter(o=>o.visibility==='shared'):mapObjects,[isGM,mapObjects,mode]);
 const filtered=displayPlaces.filter(p=>(p.name+' '+(p.zh||'')).toLowerCase().includes(search.toLowerCase()));
 const current=displayPlaces.find(p=>p.id===selected),options=displayPlaces.map(p=>({id:p.id,name:locale==='en'?p.name:(p.zh?p.zh+' · ':'')+p.name}));
 const result=useMemo(()=>planRoute(stops,travel,displayPlaces,locale),[stops,travel,displayPlaces,locale]);
 const patch=(fn:(d:AtlasData)=>AtlasData)=>{if(!canEdit)return;setData(d=>fn(d));setDirty(true)};
 function errorText(e:unknown){return e instanceof TypeError?tr("無法連線到網站伺服器，請檢查網路後重試"):e instanceof Error?e.message:tr("伺服器處理失敗。請稍後重試。")}
 function enterCampaign(j:any){setSession(j);setData(j.data);setMapObjects(j.mapObjects||[]);setMode(j.role);setDirty(false);setSelected(null);setSheet(false);setError('');setSignedOut(false);setCampaigns(cs=>[{id:j.id,role:j.role},...cs.filter(c=>c.id!==j.id)]);const url=new URL(location.href);url.searchParams.set('campaign',j.id);url.searchParams.delete('invite');history.replaceState(null,'',url)}
 async function request(body:any){let r:Response;try{r=await fetch('/api/atlas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}catch(e){throw e}const j:any=await r.json().catch(()=>({error:tr("伺服器處理失敗。請稍後重試。")}));if(!r.ok)throw Error(j.error||tr("伺服器處理失敗。請稍後重試。"));return j}
 async function load(id:string){setLoading(true);setError('');try{const r=await fetch('/api/atlas?id='+encodeURIComponent(id));const j:any=await r.json().catch(()=>({error:tr("伺服器處理失敗。請稍後重試.")}));if(!r.ok){if(j.signedOut)setSignedOut(true);throw Error(j.error||tr("載入戰役失敗。請稍後重試。"))}enterCampaign(j)}catch(e){setError(errorText(e))}finally{setLoading(false)}}
 useEffect(()=>{const u=new URL(location.href);setInvite(u.searchParams.get('invite')||'');fetch('/api/atlas').then(async r=>{const j:any=await r.json().catch(()=>({error:tr("伺服器處理失敗。請稍後重試。")}));if(!r.ok){if(j.signedOut)setSignedOut(true);else setError(j.error);return}setCampaigns(j.campaigns);const id=u.searchParams.get('campaign')||(!u.searchParams.get('invite')?j.campaigns[0]?.id:null);if(id)await load(id)}).catch(e=>setError(errorText(e))).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 async function importCampaign(file:File){setBusy(true);try{if(file.size>1500000)throw Error(tr('內容太大'));const backup=JSON.parse(await file.text());const j=await request({action:'import',backup});enterCampaign(j);toast.success(tr('戰役已匯入'))}catch(e){const message=errorText(e);setError(message);toast.error(tr(message))}finally{setBusy(false)}}
 async function start(action:string){setBusy(true);setError('');try{const j=await request({action,invite});if(action==='create')enterCampaign(j);else await load(j.id)}catch(e){const message=errorText(e);setError(message);toast.error(tr(message))}finally{setBusy(false)}}
 async function saveMap(){if(!session)return;setBusy(true);setError('');try{const j=await request({action:'save',id:session.id,revision:session.revision,data});setSession({...session,revision:j.revision,data});setDirty(false);toast.success(tr("戰役地圖已儲存"))}catch(e){const message=errorText(e);setError(message);toast.error(tr(message))}finally{setBusy(false)}}
 function canManageObject(object?:MapObject|null){return Boolean(session&&(canEdit||(session.role==='player'&&(!object||object.editable))))}
 function beginObjectPlacement(kind:MapObjectKind){if(!canManageObject())return;if(objectPlacement===kind){setObjectPlacement(null);return}setDraw(false);setMovePlace(null);setRoutePick(false);setPolygon([]);setObjectPlacement(kind);setObjectSheet(false);toast.message(tr(kind==='note'?'點擊地圖設定註記位置':'點擊地圖設定傳聞的大約範圍'))}
 function openMapObject(object:MapObject){setEditingObject(object);setObjectDraft({kind:object.kind,x:object.x,y:object.y,radius:object.radius,label:object.label,content:object.content,visibility:object.visibility});setObjectSheet(true)}
 function placeMapObject(kind:MapObjectKind,at:Point){setEditingObject(null);setObjectDraft({kind,x:at[0],y:at[1],radius:kind==='poi'?72:null,label:'',content:'',visibility:session?.role==='player'?'player_private':'gm_private'});setObjectSheet(true)}
 async function saveMapObject(){if(!session||!canManageObject(editingObject))return;if(objectDraft.kind==='note'&&!objectDraft.content.trim()){toast.error(tr('註記需要文字內容'));return}setBusy(true);setError('');try{const j=await request({action:'map-object',operation:editingObject?'update':'create',id:session.id,objectId:editingObject?.id,object:objectDraft});const saved:MapObject=j.mapObject;setMapObjects(list=>editingObject?list.map(o=>o.id===saved.id?saved:o):[...list,saved]);setEditingObject(saved);setObjectDraft({kind:saved.kind,x:saved.x,y:saved.y,radius:saved.radius,label:saved.label,content:saved.content,visibility:saved.visibility});setObjectSheet(false);toast.success(tr('地圖註記已儲存'))}catch(e){const message=errorText(e);setError(message);toast.error(tr(message))}finally{setBusy(false)}}
 async function deleteMapObject(){if(!session||!editingObject||!canManageObject(editingObject))return;setBusy(true);setError('');try{await request({action:'map-object',operation:'delete',id:session.id,objectId:editingObject.id});setMapObjects(list=>list.filter(o=>o.id!==editingObject.id));setObjectSheet(false);setEditingObject(null);toast.success(tr('地圖註記已刪除'))}catch(e){const message=errorText(e);setError(message);toast.error(tr(message))}finally{setBusy(false)}}
 async function persistMapObject(object:MapObject,origin:{x:number;y:number}){if(!session)return;try{const j=await request({action:'map-object',operation:'update',id:session.id,objectId:object.id,object:{kind:object.kind,x:object.x,y:object.y,radius:object.radius,label:object.label,content:object.content,visibility:object.visibility}});setMapObjects(list=>list.map(o=>o.id===object.id?j.mapObject:o))}catch(e){setMapObjects(list=>list.map(o=>o.id===object.id?{...o,...origin}:o));const message=errorText(e);setError(message);toast.error(tr(message))}}
 function startObjectDrag(e:any,object:MapObject){if(!canManageObject(object))return;e.preventDefault();e.stopPropagation();dragObject.current={id:object.id,x:e.clientX,y:e.clientY,origin:{x:object.x,y:object.y},moved:false};e.currentTarget.setPointerCapture(e.pointerId)}
 function moveObjectDrag(e:any){const current=dragObject.current;if(!current)return;if(Math.abs(e.clientX-current.x)+Math.abs(e.clientY-current.y)>5)current.moved=true;if(current.moved){const p=point(e);current.position={x:p[0],y:p[1]};setMapObjects(list=>list.map(o=>o.id===current.id?{...o,...current.position}:o))}}
 function endObjectDrag(){const current=dragObject.current;if(!current)return;dragObject.current=null;if(!current.moved)return;skipClick.current=true;const object=mapObjects.find(o=>o.id===current.id);if(object)void persistMapObject({...object,...current.position},current.origin)}
 function openPlace(p:Place){setSelected(p.id);setDraft({info:p.info,gmNotes:p.gmNotes||'',note:session?.notes[p.id]||'',faction:p.faction,hidden:p.hidden});setSheet(true)}
 function focusPlace(p:Place){if(p.offmap){openPlace(p);return}setView({x:p.x-65,y:p.y-60,w:130,h:120});openPlace(p)}
 function clickedPlace(p:Place){if(skipClick.current){skipClick.current=false;return}if(draw)return;if(routePick){setStops(s=>s.length>=10?s:[...s,p.id]);toast.success(tr("已加入 ")+p.name);return}openPlace(p)}
 async function saveDetails(){if(!current||!session)return;if(canEdit){const updated={...data,places:data.places.map(p=>p.id===current.id?{...p,info:draft.info,gmNotes:draft.gmNotes,faction:draft.faction,hidden:draft.hidden}:p)};setBusy(true);setError('');try{const j=await request({action:'save',id:session.id,revision:session.revision,data:updated});setData(updated);setSession({...session,data:updated,revision:j.revision});setDirty(false);toast.success(tr("地點與地圖已儲存"));setSheet(false)}catch(e){const message=errorText(e);setError(message);toast.error(tr(message))}finally{setBusy(false)}}else{setBusy(true);setError('');try{await request({action:'note',id:session.id,location:current.id,body:draft.note});setSession({...session,notes:{...session.notes,[current.id]:draft.note}});toast.success(tr("你的筆記已儲存"))}catch(e){const message=errorText(e);setError(message);toast.error(tr(message))}finally{setBusy(false)}}}
 function point(e:{clientX:number;clientY:number}):Point{const s=svg.current!;const p=s.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform(s.getScreenCTM()!.inverse());return [Math.max(0,Math.min(1000,v.x)),Math.max(0,Math.min(MAP_HEIGHT,v.y))]}
 function canvasClick(e:React.MouseEvent){if(skipClick.current){skipClick.current=false;return}const p=point(e);if(objectPlacement){placeMapObject(objectPlacement,p);setObjectPlacement(null);return}if(draw){setPolygon(s=>[...s,p]);return}if(movePlace){patch(d=>({...d,places:d.places.map(i=>i.id===movePlace?{...i,x:p[0],y:p[1],offmap:false,approx:true}:i)}));setMovePlace(null);toast.success(tr("座標已更新，請儲存地圖"))}}
 function zoom(f:number){setView(v=>{const w=Math.max(60,Math.min(1100,v.w*f)),h=v.h*w/v.w;return{x:v.x+(v.w-w)/2,y:v.y+(v.h-h)/2,w,h}})}
 function finishPolygon(){if(polygon.length<3||!activeFaction)return;patch(d=>({...d,territories:[...d.territories,{id:crypto.randomUUID(),faction:activeFaction,points:polygon}]}));setDraw(false);setPolygon([]);toast.success(tr("疆界已畫好，請儲存地圖"))}
 function exportCampaign(){if(!session||!canEdit)return;const payload={format:'dnd-map-backup',version:1,data,notes:session.notes};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='dnd-map-'+session.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function addFaction(){if(!factionName.trim())return;const id=crypto.randomUUID();patch(d=>({...d,factions:[...d.factions,{id,name:factionName.trim(),color:factionColor}]}));setActiveFaction(id);setFactionName('')}
 const mapScale=view.w/900;
 return <TooltipProvider><Toaster richColors position="top-center"/><main className="atlas-app"><header className="topbar"><div className="brand"><Compass size={27}/><div><h1>{tr("費倫")}<span>{tr("風暴行旅圖")}</span></h1><small>THE SAVAGE FRONTIER</small></div></div><div className="chapter-tag">DND Map <span>/ made by Martin Y / {tr("版本")} v0.2.0</span></div><div className="header-actions"><div className="language-switch" role="group" aria-label="Language / 語言"><button lang="zh-Hant" aria-pressed={locale==='zh'} onClick={()=>setLocale('zh')}>中文</button><button lang="en" aria-pressed={locale==='en'} onClick={()=>setLocale('en')}>EN</button></div>{session&&<><Tabs value={mode} onValueChange={v=>{setMode(v);setDraw(false);setMovePlace(null);setSheet(false)}}><TabsList><TabsTrigger value="gm" disabled={!isGM}><Shield size={15}/>GM</TabsTrigger><TabsTrigger value="player"><Users size={15}/>{tr("玩家")}{isGM?tr("預覽"):''}</TabsTrigger></TabsList></Tabs>{isGM&&<button className="primary compact" disabled={busy||!dirty} onClick={saveMap}><Save size={16}/>{busy?tr("儲存中"):dirty?tr("儲存變更"):tr("已儲存")}</button>}</>}</div></header>
 <div className="workspace"><aside className="sidebar"><div className="campaign-heading"><div className="eyebrow">{tr("北地遠征手冊")}</div><h2>{tr("下一站，往哪裡？")}</h2><p>{session?(canEdit?tr("GM 工作台 · 筆記與疆界編輯"):isGM?tr("玩家視角 · 私密內容已隱藏"):tr("玩家工作台 · 個人冒險筆記")):tr("探索北地，規劃你的旅程。")}</p></div>
 {error&&<div className="notice error">{tr(error)}<button onClick={()=>session?load(session.id):location.reload()}>{tr("重新載入")}</button></div>}
 {!session&&<div className="onboarding">{loading?<p>{tr("正在載入戰役…")}</p>:signedOut?<><p>{tr("登入後建立 GM 戰役，或加入玩家隊伍。")}</p><a className="primary" href={'/login'} target="_top">{tr("登入")}</a></>:<><button className="primary" onClick={()=>start('create')} disabled={busy}>{tr("建立我的 GM 戰役")}</button><div className="join"><input aria-label={tr("玩家邀請碼")} value={invite} onChange={e=>setInvite(e.target.value)} placeholder={tr("輸入 GM 提供的邀請碼")}/><button disabled={busy||!invite} onClick={()=>start('join')}>{tr("加入")}</button></div>{campaigns.length>0&&<Pick value="" label={tr("開啟既有戰役")} items={campaigns.map(c=>({id:c.id,name:(c.role==='gm'?'GM':tr("玩家"))+' · '+c.id.slice(0,8)}))} onChange={load}/>}</>}</div>}
 <Tabs value={tab} onValueChange={setTab} className="work-tabs"><TabsList><TabsTrigger value="route"><Route/>{tr("旅程")}</TabsTrigger><TabsTrigger value="locations"><MapPin/>{tr("地點")}</TabsTrigger><TabsTrigger value="factions"><Layers/>{tr("陣營")}</TabsTrigger></TabsList>
 <TabsContent value="route"><div className="section-label">{tr("旅程路線 ")}<span>{stops.filter(Boolean).length} {tr(" 站")}</span></div><div className="stops">{stops.map((id,i)=><div className="stop" key={i}><span className={'stop-number '+(i===0?'first':'')}>{i===0?'A':i===stops.length-1?'B':i}</span><Pick label={i===0?tr("選擇出發地"):i===stops.length-1?tr("選擇目的地"):tr("選擇中繼站")} value={id} onChange={v=>setStops(s=>s.map((a,j)=>i===j?v:a))} items={options}/>{stops.length>2&&<button className="icon" aria-label={tr("移除此站")} onClick={()=>setStops(s=>s.filter((_,j)=>j!==i))}><X size={15}/></button>}{i>0&&<button className="icon" aria-label={tr("往前移一站")} onClick={()=>setStops(s=>{const a=[...s];[a[i-1],a[i]]=[a[i],a[i-1]];return a})}>↑</button>}</div>)}</div><div className="row"><button className="text-button" disabled={stops.length>=10} onClick={()=>setStops(s=>[...s.slice(0,-1),'',s[s.length-1]])}><Plus size={15}/>{tr("新增中繼站")}</button><button className={'text-button '+(routePick?'active':'')} onClick={()=>setRoutePick(!routePick)}><MousePointer2 size={15}/>{routePick?tr("結束選點"):tr("地圖選點")}</button></div><p className="hint">{tr("也可從一個地點標記拖曳到另一個，建立 A → B 路線。")}</p><div className="section-label">{tr("行進方式")}</div><Tabs value={travel} onValueChange={setTravel}><TabsList className="travel-modes"><TabsTrigger value="road">{tr("大路・城鎮補給")}</TabsTrigger><TabsTrigger value="wild">{tr("越野・穿越地形")}</TabsTrigger></TabsList></Tabs>
 <div className="journey-result"><div className="eyebrow">{tr("預估行程")}</div>{result.error?<p className="route-error">{result.error}</p>:<><div className="distance">{Math.round(result.miles)}<span>{tr("英里")}</span></div><div className="result-meta"><span><Navigation size={15}/>{result.days.toFixed(1)} {tr(" 天步行")}</span><span><Mountain size={15}/>{travel==='road'?tr("沿主要道路"):tr("地形加權")}</span></div><div className="route-towns">{result.towns.length?result.towns.join(' → '):tr("此段沒有已標記的城鎮補給點")}</div></>}</div><p className="hint">{tr("遊戲估算：每日 24 英里；越野依森林、山地增加耗時。道路為主要路網示意，非逐段精確測繪。海路與飛行不納入。")}</p>{result.points.length>0&&<button className="secondary full" onClick={()=>{const xs=result.points.map(p=>p[0]),ys=result.points.map(p=>p[1]);const x=Math.min(...xs),y=Math.min(...ys);setView({x:x-15,y:y-15,w:Math.max(65,Math.max(...xs)-x+30),h:Math.max(65,Math.max(...ys)-y+30)})}}>{tr("顯示完整路線")}</button>}</TabsContent>
 <TabsContent value="locations"><label className="search"><Search size={17}/><input placeholder={tr("搜尋中文 / English 地名")} aria-label={tr("搜尋地點")} value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="section-label">{tr("地點索引 ")}<span>{filtered.length} {tr(" 處")}</span></div><div className="place-list">{filtered.map(p=><button className="place-row" key={p.id} onClick={()=>focusPlace(p)}><MapPin size={15} style={{color:data.factions.find(f=>f.id===p.faction)?.color||'#d3b875'}}/><span><strong>{name(p)}</strong>{locale==='zh'&&p.zh&&<small>{p.name}</small>}</span><span className="place-meta">{p.offmap?tr("待定位"):p.chapter}{p.hidden&&<Lock size={12}/>}</span><ChevronRight size={14}/></button>)}{!filtered.length&&<p className="hint">{tr("找不到符合的地點。")}</p>}</div></TabsContent>
 <TabsContent value="factions"><div className="section-label">{tr("勢力與疆界 ")}<span>{data.factions.length} {tr(" 個")}</span></div>{!data.factions.length&&<div className="empty-state"><Flag/><p>{tr("北地的疆界，尚待你書寫。")}</p><small>{canEdit?tr("新增陣營，再在地圖上圈選領域。"):tr("GM 尚未設定陣營。")}</small></div>}{data.factions.map(f=><div className={'faction-card '+(activeFaction===f.id?'chosen':'')} key={f.id}><button className="faction-name" onClick={()=>setActiveFaction(f.id)}><i style={{background:f.color}}/>{f.name}</button>{canEdit&&<><input aria-label={tr("修改 ")+f.name+tr(" 顏色")} type="color" value={f.color} onChange={e=>patch(d=>({...d,factions:d.factions.map(a=>a.id===f.id?{...a,color:e.target.value}:a)}))}/><button className="icon" title={tr("重新命名")} onClick={()=>{const name=prompt(tr("陣營名稱"),f.name);if(name?.trim())patch(d=>({...d,factions:d.factions.map(a=>a.id===f.id?{...a,name:name.trim().slice(0,100)}:a)}))}}><Pencil size={14}/></button></>}</div>)}{canEdit&&<><div className="new-faction"><input value={factionName} onChange={e=>setFactionName(e.target.value)} maxLength={100} placeholder={tr("新增陣營名稱")} aria-label={tr("新增陣營名稱")}/><input type="color" aria-label={tr("新陣營顏色")} value={factionColor} onChange={e=>setFactionColor(e.target.value)}/><button className="icon" aria-label={tr("新增陣營")} onClick={addFaction} disabled={!factionName.trim()}><Plus/></button></div><button className="secondary full" disabled={!activeFaction} onClick={()=>{setDraw(!draw);setPolygon([])}}><Pencil size={16}/>{draw?tr("取消繪製"):tr("繪製陣營佔領區")}</button>{draw&&<div className="notice">{tr("依序點擊邊界頂點，至少 3 點。")}<div className="row"><button onClick={()=>setPolygon(p=>p.slice(0,-1))}>{tr("撤銷一點")}</button><button disabled={polygon.length<3} onClick={finishPolygon}>{tr("完成區域")}</button></div></div>}</>}{data.territories.map((t,i)=><div className="territory-row" key={t.id}><span>{data.factions.find(f=>f.id===t.faction)?.name} {tr(" · 區域 ")}{i+1}</span>{canEdit&&<button className="icon" aria-label={tr("刪除此區域")} onClick={()=>patch(d=>({...d,territories:d.territories.filter(a=>a.id!==t.id)}))}><Trash2 size={14}/></button>}</div>)}<p className="hint">{tr("疆界與城鎮陣營色彩對玩家可見。選取地點可指定所屬陣營；要修改疆界形狀，刪除原區域再重新圈選。")}</p></TabsContent></Tabs>
 <div className="sidebar-bottom">{session&&<form action="/auth/signout" method="post"><button className="text-button">{locale==='en'?'Sign out':'登出'}</button></form>}{!signedOut&&!loading&&(!session||canEdit)&&<label className="text-button">{tr("匯入戰役備份")}<input type="file" accept="application/json,.json" disabled={busy} style={{maxWidth:190}} onChange={e=>{const file=e.target.files?.[0];if(file)void importCampaign(file);e.target.value=''}}/></label>}{canEdit&&session&&<><button className="text-button" onClick={exportCampaign}>{tr("匯出戰役備份")}</button><button className="text-button" onClick={()=>setInviteShown(!inviteShown)}><LinkIcon size={15}/>{tr("玩家邀請碼")}</button>{inviteShown&&<div className="invite-box"><p>{tr("玩家登入後輸入此碼，即可加入此戰役。網站本身也須開放給該玩家。")}</p><code>{session.invite}</code><button onClick={()=>navigator.clipboard.writeText(session.invite||'').then(()=>toast.success(tr("邀請碼已複製"))).catch(()=>toast.error(tr("請手動選取複製")))}>{tr("複製")}</button></div>}</>}<div className="sources"><span>{tr("地圖 © Wizards of the Coast · Mike Schley")}</span><a href={sourceLinks.map} target="_blank" rel="noreferrer">{tr("底圖來源 ↗")}</a><a href={sourceLinks.locations} target="_blank" rel="noreferrer">{tr("章節地點 ↗")}</a><a href={sourceLinks.coordinates} target="_blank" rel="noreferrer">{tr("座標參考 AideDD ↗")}</a></div></div></aside>
 <section className="map-panel" aria-label={tr("可拖曳與縮放的費倫地圖")}><div className="map-title"><Compass size={18}/><span>{tr("劍灣與北地")}</span><small>{objectPlacement?tr(objectPlacement==='note'?'點擊地圖設定註記位置':'點擊地圖設定傳聞的大約範圍'):draw?tr("繪製模式"):movePlace?tr("點擊地圖設定位置"):routePick?tr("點選地點加入旅程"):tr("探索模式")}</small></div><div className="map-tools"><Tooltip><TooltipTrigger asChild><button aria-label={tr("放大")} onClick={()=>zoom(.75)}><Plus/></button></TooltipTrigger><TooltipContent>{tr("放大")}</TooltipContent></Tooltip><button aria-label={tr("縮小")} onClick={()=>zoom(1.33)}><Minus/></button><button aria-label={tr("回到北地")} onClick={()=>setView({x:340,y:10,w:330,h:280})}><RotateCcw size={19}/></button><button aria-label={tr("顯示整張地圖")} onClick={()=>setView({x:0,y:0,w:1000,h:MAP_HEIGHT})}><Compass size={19}/></button>{canManageObject()&&<><button className={objectPlacement==='note'?'active':''} aria-label={tr("新增地圖註記")} title={tr("新增地圖註記")} onClick={()=>beginObjectPlacement('note')}><StickyNote size={18}/></button><button className={objectPlacement==='poi'?'active':''} aria-label={tr("新增傳聞 POI")} title={tr("新增傳聞 POI")} onClick={()=>beginObjectPlacement('poi')}><TriangleAlert size={18}/></button></>}</div>
 <svg ref={svg} role="group" aria-label={tr("地圖地點標記")} data-map-layer-order={MAP_LAYER_ORDER.join(' > ')} className={'world-map '+(draw||movePlace||objectPlacement?'drawing':'')} viewBox={`${view.x} ${view.y} ${view.w} ${view.h}`} preserveAspectRatio="xMidYMid meet" onDragStart={e=>e.preventDefault()} onWheel={e=>{zoom(e.deltaY>0?1.1:.9)}} onClick={canvasClick} onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,v:view,moved:false};svg.current?.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(dragObject.current){moveObjectDrag(e);return}if(!drag.current||draw||movePlace||objectPlacement||dragMarker.current)return;const d=drag.current;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>5){d.moved=true;const box=svg.current!.getBoundingClientRect();const factor=Math.max(d.v.w/box.width,d.v.h/box.height);setView({...d.v,x:d.v.x-dx*factor,y:d.v.y-dy*factor})}}} onPointerUp={e=>{if(dragObject.current){endObjectDrag();return}if(dragMarker.current){const p=point(e),near=displayPlaces.filter(a=>!a.offmap).sort((a,b)=>Math.hypot(a.x-p[0],a.y-p[1])-Math.hypot(b.x-p[0],b.y-p[1]))[0];if(Math.hypot(e.clientX-markerStart.current[0],e.clientY-markerStart.current[1])<6){const original=displayPlaces.find(p=>p.id===dragMarker.current);if(original)clickedPlace(original);skipClick.current=true}else if(near&&near.id!==dragMarker.current&&Math.hypot(near.x-p[0],near.y-p[1])<view.w*.04){setStops([dragMarker.current,near.id]);setTab('route');skipClick.current=true;toast.success(tr("已建立路線"))}else if(near&&near.id===dragMarker.current&&Math.hypot(near.x-p[0],near.y-p[1])<view.w*.04){clickedPlace(near);skipClick.current=true}dragMarker.current=null}else if(drag.current?.moved)skipClick.current=true;drag.current=null}} onPointerCancel={()=>{drag.current=null;dragMarker.current=null;if(dragObject.current){const d=dragObject.current;setMapObjects(list=>list.map(o=>o.id===d.id?{...o,...d.origin}:o));dragObject.current=null}}}>
 <g data-map-layer="base-map"><image href="/sword-coast.webp" x="0" y="0" width="1000" height={MAP_HEIGHT}/></g>
 <g data-map-layer="factions">{showRegions&&data.territories.map(t=>{const color=data.factions.find(f=>f.id===t.faction)?.color||'#d09251';return <polygon key={t.id} points={t.points.map(p=>p.join(',')).join(' ')} fill={color} fillOpacity=".28" stroke={color} strokeWidth={1.6*mapScale} strokeDasharray={`${5*mapScale} ${3*mapScale}`} pointerEvents="none"/>})}</g>
 <g data-map-layer="locations">{displayPlaces.filter(p=>!p.offmap).map(p=>{const color=data.factions.find(f=>f.id===p.faction)?.color||'#233e44',index=stops.indexOf(p.id),r=(index>=0?7:4)*mapScale;return <g key={p.id} role="button" aria-label={p.name} tabIndex={0} className="map-marker" pointerEvents="bounding-box" onKeyDown={e=>{if(e.key==='Enter')clickedPlace(p)}} onPointerDown={e=>{if(draw||movePlace||objectPlacement)return;e.preventDefault();e.stopPropagation();dragMarker.current=p.id;markerStart.current=[e.clientX,e.clientY];svg.current?.setPointerCapture(e.pointerId)}} onClick={e=>{if(draw||movePlace||objectPlacement)return;e.stopPropagation();clickedPlace(p)}} onMouseEnter={e=>{if(!drag.current&&!draw)setHover({p,x:e.clientX,y:e.clientY})}} onMouseLeave={()=>setHover(null)}><circle cx={p.x} cy={p.y} r={r+4*mapScale} fill="transparent"/><circle cx={p.x} cy={p.y} r={r} fill={index>=0?'#ad532e':color} stroke="#ffedbf" strokeWidth={1.5*mapScale} opacity={p.hidden?.65:1}/>{index>=0&&<text x={p.x} y={p.y+3*mapScale} textAnchor="middle" fontSize={8*mapScale} fill="white" fontWeight="bold" pointerEvents="none">{index===0?'A':index===stops.length-1?'B':index}</text>}{showLabels&&(view.w<240||index>=0||['Waterdeep','Neverwinter','Triboar','Yartar','Silverymoon','Everlund','Bryn Shander','Luskan','Mirabar'].includes(p.name))&&<text x={p.x+8*mapScale} y={p.y+3*mapScale} fill={color} stroke="#f8ebc7" strokeWidth={3*mapScale} paintOrder="stroke" fontSize={12*mapScale} fontWeight="700" pointerEvents="none">{name(p)}</text>}</g>})}{draw&&polygon.length>0&&<><polyline points={polygon.map(p=>p.join(',')).join(' ')} fill={factionColor} fillOpacity=".2" stroke="#ab4936" strokeWidth={2*mapScale}/>{polygon.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r={4*mapScale} fill="#ab4936"/>)}</>}</g>
 {/* Future Fog of War slot: keep it between world-state locations and player knowledge. */}
 <g data-map-layer="fog-of-war" aria-hidden="true" />
 <g data-map-layer="routes">{result.points.length>1&&<><polyline points={result.points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#fff8dc" strokeWidth={6*mapScale} strokeLinejoin="round" pointerEvents="none"/><polyline points={result.points.map(p=>p.join(',')).join(' ')} fill="none" stroke={travel==='road'?'#ad532e':'#397d71'} strokeWidth={3*mapScale} strokeDasharray={travel==='wild'?`${7*mapScale} ${4*mapScale}`:undefined} strokeLinejoin="round" pointerEvents="none"/></>}</g>
 <g data-map-layer="map-objects"><defs><filter id="poi-soft-glow" x="-70%" y="-70%" width="240%" height="240%"><feGaussianBlur stdDeviation={5*mapScale}/></filter></defs>{displayMapObjects.map(object=>{const editable=canManageObject(object),title=object.label||object.content;return object.kind==='poi'?<g key={object.id} role="button" aria-label={title||tr('傳聞 POI')} tabIndex={0} className={'poi-marker '+(editable?'editable':'')} onKeyDown={e=>{if(e.key==='Enter')openMapObject(object)}} onPointerDown={e=>startObjectDrag(e,object)} onClick={e=>{e.stopPropagation();if(skipClick.current){skipClick.current=false;return}openMapObject(object)}}><circle cx={object.x} cy={object.y} r={object.radius||72} fill="#dc6d36" opacity=".27" filter="url(#poi-soft-glow)" pointerEvents="none"/><circle cx={object.x} cy={object.y} r={object.radius||72} fill="#ed9550" fillOpacity=".12" stroke="#8a3428" strokeWidth={2*mapScale} strokeDasharray={`${7*mapScale} ${6*mapScale}`} pointerEvents="none"/><text x={object.x} y={object.y+13*mapScale} textAnchor="middle" fontSize={42*mapScale} fontWeight="900" fill="#7b271f" stroke="#f8dfb2" strokeWidth={2*mapScale} paintOrder="stroke" filter="url(#poi-soft-glow)" pointerEvents="none">!</text>{object.label&&<text x={object.x} y={object.y+(object.radius||72)+15*mapScale} textAnchor="middle" fontSize={11*mapScale} fontWeight="700" fill="#49332a" stroke="#f4e2bd" strokeWidth={3*mapScale} paintOrder="stroke" pointerEvents="none">{object.label.slice(0,36)}</text>}</g>:<g key={object.id} role="button" aria-label={title||tr('地圖註記')} tabIndex={0} className={'map-note-marker '+(editable?'editable':'')} onKeyDown={e=>{if(e.key==='Enter')openMapObject(object)}} onPointerDown={e=>startObjectDrag(e,object)} onClick={e=>{e.stopPropagation();if(skipClick.current){skipClick.current=false;return}openMapObject(object)}}><rect x={object.x-66*mapScale} y={object.y-20*mapScale} width={132*mapScale} height={40*mapScale} rx={4*mapScale} fill="#f5e7c5" stroke="#6b5034" strokeWidth={1.5*mapScale}/><text x={object.x-56*mapScale} y={object.y-4*mapScale} fontSize={10*mapScale} fontWeight="700" fill="#352d25" pointerEvents="none">{(object.label||object.content).slice(0,24)}</text><text x={object.x-56*mapScale} y={object.y+10*mapScale} fontSize={8*mapScale} fill="#574b3c" pointerEvents="none">{object.content.slice(0,28)}</text></g>})}</g>
 </svg>
 <div className="map-bottom"><div className="map-options"><label><Checkbox checked={showLabels} onCheckedChange={v=>setShowLabels(v===true)}/>{tr("地名")}</label><label><Checkbox checked={showRegions} onCheckedChange={v=>setShowRegions(v===true)}/>{tr("陣營疆界")}</label></div><span>{tr("拖曳平移 · 滾輪縮放 · 點擊地點")}</span></div>{hover&&!sheet&&<div className="map-hover" style={{left:Math.min(hover.x+14,(typeof window!=='undefined'?window.innerWidth:1200)-280),top:Math.max(80,Math.min(hover.y+12,(typeof window!=='undefined'?window.innerHeight:900)-170))}}><strong>{name(hover.p)}</strong>{locale==='zh'&&hover.p.zh&&<small>{hover.p.name}</small>}<p>{hover.p.info||tr("尚無地點資訊")}</p><span>{hover.p.chapter}{hover.p.approx?tr(" · 位置約略"):''}</span></div>}
 </section></div>
 <Sheet open={sheet} onOpenChange={setSheet}><SheetContent className="detail-sheet"><SheetHeader><div className="eyebrow">{current?.chapter} · {tr(current?.kind||'')}</div><SheetTitle>{current?name(current):''}</SheetTitle><SheetDescription>{locale==='zh'&&current?.zh?current.name:tr("地點檔案")}{current?.approx?tr(" · 位置約略，可由 GM 調整"):''}{current?.offmap?tr(" · 尚待定位"):''}</SheetDescription></SheetHeader>{current&&<div className="detail-body"><div className="row"><button className="secondary" onClick={()=>{setStops(s=>[current.id,...s.slice(1)]);setSheet(false);setTab('route')}}>{tr("設為起點")}</button><button className="secondary" onClick={()=>{setStops(s=>[...s.slice(0,-1),current.id]);setSheet(false);setTab('route')}}>{tr("設為終點")}</button></div><label className="field-label">{tr("地點資訊")}{canEdit?tr(" · 玩家可見"):''}</label>{canEdit?<textarea value={draft.info} maxLength={20000} onChange={e=>setDraft({...draft,info:e.target.value})} placeholder={tr("留白，等待你補上這裡的故事…")}/>:<div className="read-note">{current.info||tr("尚無地點資訊")}</div>}{canEdit?<><label className="field-label">{tr("所屬陣營")}</label><Pick value={draft.faction} onChange={faction=>setDraft({...draft,faction})} items={data.factions} label={tr("未指定")}/><label className="checkbox-label"><Checkbox checked={draft.hidden} onCheckedChange={v=>setDraft({...draft,hidden:v===true})}/>{tr("對玩家隱藏此地點")}</label><p className="hint">{tr("只隱藏互動標記。底圖上的既有印刷地名不受影響。")}</p><label className="field-label"><Lock size={14}/>{tr("GM notes · 僅 GM 可見")}</label><textarea className="gm-note" value={draft.gmNotes} maxLength={20000} onChange={e=>setDraft({...draft,gmNotes:e.target.value})} placeholder={tr("秘密、伏筆、遭遇與準備事項…")}/><button className="text-button" onClick={()=>{setMovePlace(current.id);setSheet(false)}}><MapPin size={15}/>{tr("在地圖上重新定位")}</button></>:<><label className="field-label"><Pencil size={14}/>{tr("Player notes · 僅自己可見")}</label><textarea value={draft.note} maxLength={20000} disabled={!session} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder={tr("記錄傳聞、補給與冒險心得…")}/></>}<button className="primary full" disabled={busy||!session} onClick={saveDetails}><Save size={16}/>{busy?tr("儲存中"):canEdit?tr("儲存地點與地圖"):tr("儲存我的筆記")}</button></div>}</SheetContent></Sheet>
 <Sheet open={objectSheet} onOpenChange={setObjectSheet}><SheetContent className="detail-sheet"><SheetHeader><div className="eyebrow">{tr(objectDraft.kind==='poi'?'近似情報':'地圖註記')} · {tr('地圖座標')}</div><SheetTitle>{tr(editingObject?'編輯地圖標記':objectDraft.kind==='poi'?'新增傳聞 POI':'新增文字註記')}</SheetTitle><SheetDescription>{tr('標記會固定在地圖座標上；拖曳地圖標記可移動。')}</SheetDescription></SheetHeader><div className="detail-body"><label className="field-label">{tr('標題，可留空')}</label><input value={objectDraft.label} maxLength={160} disabled={!canManageObject(editingObject)} onChange={e=>setObjectDraft({...objectDraft,label:e.target.value})} placeholder={tr(objectDraft.kind==='poi'?'例如：北方的傳聞':'註記標題')}/>{objectDraft.kind==='note'&&<><label className="field-label">{tr('註記文字')}</label><textarea required value={objectDraft.content} maxLength={20000} disabled={!canManageObject(editingObject)} onChange={e=>setObjectDraft({...objectDraft,content:e.target.value})} placeholder={tr('寫下地圖註記…')}/></>}{objectDraft.kind==='poi'&&<><label className="field-label">{tr('線索補充，可留空')}</label><textarea value={objectDraft.content} maxLength={20000} disabled={!canManageObject(editingObject)} onChange={e=>setObjectDraft({...objectDraft,content:e.target.value})} placeholder={tr('描述這項情報，不代表精確座標。')}/><label className="field-label">{tr('不確定範圍')} · {Math.round(objectDraft.radius||72)}</label><input type="range" min={18} max={180} step={2} value={objectDraft.radius||72} disabled={!canManageObject(editingObject)} onChange={e=>setObjectDraft({...objectDraft,radius:Number(e.target.value)})}/></>}
 <label className="field-label">{tr('可見範圍')}</label><Pick value={objectDraft.visibility} onChange={v=>setObjectDraft({...objectDraft,visibility:v as MapObjectVisibility})} label={tr('可見範圍')} items={[...(session?.role==='gm'?[{id:'gm_private',name:tr('僅 GM 可見')}]:[]),{id:'player_private',name:tr('僅自己可見')},{id:'shared',name:tr('戰役成員可見')}]}/><div className="hint">{tr('GM 私密標記只會由伺服器傳回 GM，不會送到玩家瀏覽器。座標是地圖座標，不是螢幕位置。')}</div>{canManageObject(editingObject)?<div className="row object-actions"><button className="primary" disabled={busy||objectDraft.kind==='note'&&!objectDraft.content.trim()} onClick={saveMapObject}><Save size={15}/>{busy?tr('儲存中'):tr('儲存標記')}</button>{editingObject&&<button className="secondary danger" disabled={busy} onClick={deleteMapObject}><Trash2 size={15}/>{tr('刪除')}</button>}</div>:<div className="read-note">{objectDraft.content||objectDraft.label||tr('沒有補充內容')}</div>}</div></SheetContent></Sheet>
 </main></TooltipProvider>
}
