import {translate,placeName,type Locale} from './i18n';
import {roadChains,roads,milesPerUnit,MAP_HEIGHT} from './geography';
import type {Place,Point} from './types';
export type RouteResult={points:Point[];miles:number;days:number;towns:string[];error?:string};
const dist=(a:Point,b:Point)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const empty=(error:string):RouteResult=>({points:[],miles:0,days:0,towns:[],error});
const coast:Point[]=[[20,310],[30,325],[40,338],[50,342],[60,340],[70,337],[80,355],[88,385],[100,389],[120,391],[140,398],[160,404],[180,410],[200,417],[220,434],[240,448],[260,466],[280,476],[300,480],[340,490],[370,502],[420,511],[470,519],[530,523],[580,537],[647,535]];
function land(x:number,y:number){if(x<0||x>985||y<20||y>MAP_HEIGHT-15)return false;for(let i=1;i<coast.length;i++)if(y<=coast[i][0]){const a=coast[i-1],b=coast[i];return x>=a[1]+(b[1]-a[1])*(y-a[0])/(b[0]-a[0])}return false;}
const ellipse=(x:number,y:number,cx:number,cy:number,rx:number,ry:number)=>((x-cx)/rx)**2+((y-cy)/ry)**2<1;
function terrain(x:number,y:number){if(!land(x,y))return Infinity;if(y<59&&x>370&&x<690)return 2.8;if(ellipse(x,y,620,196,20,60)||ellipse(x,y,554,170,13,22)||ellipse(x,y,438,190,13,20)||ellipse(x,y,606,101,40,7))return 2.5;if(ellipse(x,y,566,170,61,48)||ellipse(x,y,479,73,37,22)||ellipse(x,y,425,116,21,21)||ellipse(x,y,453,171,15,24)||ellipse(x,y,586,53,48,20)||ellipse(x,y,516,281,19,20))return 2;if(ellipse(x,y,524,123,30,18)||ellipse(x,y,559,291,45,28))return 2;return 1.15;}
function roadLeg(a:Place,b:Place,places:Place[]):Point[]|null{const nodes=new Map(places.map(p=>[p.id,p])),graph=new Map<string,string[]>();for(const chain of roadChains)for(let i=1;i<chain.length;i++){const u=chain[i-1],v=chain[i];if(!nodes.has(u)||!nodes.has(v))continue;graph.set(u,[...(graph.get(u)||[]),v]);graph.set(v,[...(graph.get(v)||[]),u]);}if(!graph.has(a.id)||!graph.has(b.id))return null;const ds=new Map([[a.id,0]]),prev=new Map<string,string>(),q=new Set(graph.keys());while(q.size){let u='';let best=Infinity;for(const k of q){const v=ds.get(k)??Infinity;if(v<best){best=v;u=k}}if(!u)break;if(u===b.id)break;q.delete(u);for(const v of graph.get(u)||[]){const p=nodes.get(u)!,r=nodes.get(v)!,nd=best+dist([p.x,p.y],[r.x,r.y]);if(nd<(ds.get(v)??Infinity)){ds.set(v,nd);prev.set(v,u)}}}if(!ds.has(b.id))return null;const ids=[b.id];while(ids[0]!==a.id){const p=prev.get(ids[0]);if(!p)return null;ids.unshift(p)}return ids.map(id=>{const p=nodes.get(id)!;return [p.x,p.y]});}
class Heap{a:{id:number;cost:number}[]=[];push(v:{id:number;cost:number}){let i=this.a.length;this.a.push(v);while(i){const p=(i-1)>>1;if(this.a[p].cost<=v.cost)break;this.a[i]=this.a[p];i=p}this.a[i]=v;}pop(){const out=this.a[0],v=this.a.pop()!;if(this.a.length){let i=0;while(i*2+1<this.a.length){let c=i*2+1;if(c+1<this.a.length&&this.a[c+1].cost<this.a[c].cost)c++;if(this.a[c].cost>=v.cost)break;this.a[i]=this.a[c];i=c;}this.a[i]=v;}return out;}}
function wildLeg(a:Place,b:Place):Point[]|null{const step=2,W=501,H=324,toId=(x:number,y:number)=>Math.round(y/step)*W+Math.round(x/step),from=(id:number):Point=>[(id%W)*step,Math.floor(id/W)*step];if(!land(a.x,a.y)||!land(b.x,b.y))return null;const start=toId(a.x,a.y),end=toId(b.x,b.y),cost=new Float64Array(W*H).fill(Infinity),prev=new Int32Array(W*H).fill(-1),closed=new Uint8Array(W*H),heap=new Heap();cost[start]=0;heap.push({id:start,cost:0});while(heap.a.length){const {id}=heap.pop();if(closed[id])continue;if(id===end){const out:Point[]=[];let n=end;while(n!==-1){out.push(from(n));n=prev[n]}out.reverse();out[0]=[a.x,a.y];out[out.length-1]=[b.x,b.y];return out;}closed[id]=1;const [x,y]=from(id);for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){if(!dx&&!dy)continue;const nx=x+dx*step,ny=y+dy*step;if(nx<0||nx>=W*step||ny<0||ny>=H*step)continue;const n=toId(nx,ny);if(closed[n])continue;const t=terrain(nx,ny);if(!Number.isFinite(t))continue;if(dx&&dy&&(!land(x+dx*step,y)||!land(x,y+dy*step)))continue;const nd=cost[id]+Math.hypot(dx,dy)*step*t;if(nd<cost[n]){cost[n]=nd;prev[n]=id;heap.push({id:n,cost:nd+dist([nx,ny],[b.x,b.y])*1.15})}}}return null;}
export function planRoute(ids:string[],mode:string,places:Place[],locale:Locale='zh'):RouteResult{const tr=(text:string)=>translate(text,locale);const name=(p:Place)=>placeName(p,locale);if(ids.length<2||ids.some(id=>!id))return empty(tr('選擇起點、終點與所需中繼站。'));const stops=ids.map(id=>places.find(p=>p.id===id));if(stops.some(p=>!p))return empty(tr('某個地點不在目前可見的地圖中。'));if(stops.some(p=>p!.offmap))return empty(tr('移動地點尚未定位，請先請 GM 設定座標。'));let points:Point[]=[];for(let i=1;i<stops.length;i++){const a=stops[i-1]!,b=stops[i]!;if(a.id===b.id)continue;const leg=mode==='road'?roadLeg(a,b,places):wildLeg(a,b);if(!leg)return empty(mode==='road'?`${name(a)} → ${name(b)} ${tr('不在已建置的主要道路路網上。改用越野，或選擇沿路城鎮。')}`:tr('這段旅程涉及海域或超出陸路範圍，無法估算。請選擇陸上地點。'));points.push(...(points.length?leg.slice(1):leg));}let miles=0,weighted=0;for(let i=1;i<points.length;i++){const d=dist(points[i-1],points[i])*milesPerUnit;miles+=d;weighted+=d*(mode==='road'?1:terrain(...points[i]));}const townIds=new Set(roadChains.flat()),towns=places.filter(p=>townIds.has(p.id)&&points.some(a=>dist(a,[p.x,p.y])<1.8)).sort((a,b)=>points.findIndex(p=>dist(p,[a.x,a.y])<1.8)-points.findIndex(p=>dist(p,[b.x,b.y])<1.8)).map(p=>name(p));return{points,miles,days:weighted/24,towns};}
